trigger:
- '*'

variables:
  buildConfiguration: 'Release'
  leaderboardRepository: 'leaderboard'
  webRepository: 'web'
  tag: '$(Build.BuildId)'
  imagePullSecret: 'secret'

stages:
- stage: 'Build'
  displayName: 'Build and push'
  jobs:  
  - job: 'Build'
    displayName: 'Build job'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: 'Build and push the image to container registry'
      inputs:
        command: buildAndPush
        buildContext: $(Build.Repository.LocalPath)
        repository: $(webRepository)
        dockerfile: '$(Build.SourcesDirectory)/ADO.UseCase.Docker.Kubernetes/Dockerfile'
        containerRegistry: 'ado-use-case-dockkuber-connection'
        tags: |
          $(tag)

    - publish: '$(Build.SourcesDirectory)/manifests'
      artifact: manifests

- stage: 'Deploy'
  displayName: 'Deploy the containers'
  dependsOn: Build
  jobs:
  - deployment: Deploy
    displayName: Deploy
    pool:
      vmImage: 'ubuntu-latest'
    environment: 'ado-use-case-dockkuber-env'
    variables:
    - group: ado-use-case-variables
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: manifests

          - task: KubernetesManifest@1
            displayName: Create imagePullSecret
            inputs:
                  action: createSecret
                  connectionType: azureResourceManager
                  secretName: $(imagePullSecret)
                  dockerRegistryEndpoint: 'ado-use-case-dockkuber-connection'
                  azureSubscriptionConnection: 'ado-use-case-arm-connection'
                  azureResourceGroup: 'ado-use-case-resource-group'
                  kubernetesCluster: 'ado-use-case-dockkuber-001'
                  namespace: 'default'

          - task: KubernetesManifest@1
            displayName: Deploy to Kubernetes cluster
            inputs:
                action: deploy
                connectionType: azureResourceManager
                azureSubscriptionConnection: 'ado-use-case-arm-connection'
                azureResourceGroup: 'ado-use-case-resource-group'
                kubernetesCluster: 'ado-use-case-dockkuber-001'
                progressDeadlineSeconds: 3600
                namespace: 'default'
                manifests: |
                  $(Pipeline.Workspace)/manifests/deployment.yml
                  $(Pipeline.Workspace)/manifests/service.yml
                imagePullSecrets: |
                  $(imagePullSecret)
                containers: |
                  $(RegistryName)/$(webRepository):$(tag)
                  $(RegistryName)/$(leaderboardRepository):$(tag)

                # b